export const ADD_REPEATER_REQUEST = 'ADD_REPEATER_REQUEST';
export const UPDATE_REPEATER_REQUEST = 'UPDATE_REPEATER_REQUEST';
export const REMOVE_REPEATER_REQUEST = 'REMOVE_REPEATER_REQUEST';
export const CLEAR_REPEATER_REQUESTS = 'CLEAR_REPEATER_REQUESTS';
