export const ADD_REPEATER_DATA = 'ADD_REPEATER_DATA';
export const ADD_REPEATER_BULK_DATA = 'ADD_REPEATER_BULK_DATA';
export const REMOVE_REPEATER_DATA = 'REMOVE_REPEATER_DATA';
export const CLEAR_REPEATER_DATA = 'CLEAR_REPEATER_DATA';
